# This is a workflow to spell check.

name: alitheia-spell-checker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        cd $GITHUB_WORKSPACE
        pip install -r requirements.txt
        export PYTHONPATH=$PYTHONPATH:`pwd`/
        pylint --load-plugins alitheia_spell_checker sample.py | sudo tee /tmp/alitheia-spell-check.txt
        export SPELLING_ERRORS=`cat /tmp/alitheia-spell-check.txt | grep C1991 | wc -l`" spelling errors"
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
        
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: junit/test-results.xml
      if: ${{ always() }}
    
    - name: Upload alitheia spell check test results
      uses: actions/upload-artifact@v2
      with:
        name: spellcheck-results
        path: /tmp/alitheia-spell-check.txt
      if: ${{ always() }}

    - name: Update badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET}}
        gistID: 3c94642138181608e5b97f4eccec6da8
        filename: alitheia-spell-check-badge.json
        label: alitheia
        message: ${{ env.SPELLING_ERRORS }}
        COLOR: orange